### ISSUE TITLE
While gulp serve getting error 

### ISSUE THREAD

**Issue by spo365** [ravichandran-blog/SPFx#2]
While gulp serve getting error 

node_modules/@uifabric/foundation/lib/ISlots.d.ts(69,124): error TS1005: ')' expected.

blog link :- https://ravichandran.blog/2020/04/11/simple-list-operations-in-spfx-using-pnpjs/

**Comment by ravichandran-blog** [comment]
Can you try this?
https://github.com/microsoft/fluentui/issues/8458#issuecomment-478388791
