### ISSUE TITLE
Error build the webpart

### ISSUE THREAD

**Issue by gselvag** [ravichandran-blog/SPFx#3]
I get following error when building the webpart:

Error - [tsc] src/webparts/spfxFluentuiNav/components/SpfxFluentuiNav.tsx(105,15): error TS2739: Type '{ key: any; label: any; data: any; children: undefined[]; }' is missing the following properties from type 'INavLink': name, url
Error - [tsc] src/webparts/spfxFluentuiNav/components/SpfxFluentuiNav.tsx(111,22): error TS2345: Argument of type 'INavLink' is not assignable to parameter of type 'INavLinkGroup'.
Error - [tsc] src/webparts/spfxFluentuiNav/components/SpfxFluentuiNav.tsx(114,15): error TS2739: Type '{ key: any; label: any; data: any; }' is missing the following properties from type 'INavLink': name, url
Error - [tsc] src/webparts/spfxFluentuiNav/components/SpfxFluentuiNav.tsx(119,13): error TS2322: Type 'INavLinkGroup[]' is not assignable to type 'INavLink[]'.
Error - [tsc] src/webparts/spfxFluentuiNav/components/SpfxFluentuiNav.tsx(119,87): error TS2339: Property 'key' does not exist on type 'INavLinkGroup'.
Error - 'tsc' sub task errored after 6.28 s 
 exited with code 2

There are type issues.

**Comment by ravichandran-blog** [comment]
Can you please refer my new changes
https://github.com/ravichandran-blog/SPFx/blob/master/spfx-fluentui-nav/src/webparts/spfxFluentuiNav/components/SpfxFluentuiNav.tsx
